/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.ConsultaM;

import controller.ConsultaDao;
import controller.conn;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author joelmir
 *//**
 *
 * @author joelmir
 */
public class Principal extends javax.swing.JFrame {
    ConsultaDao Cdao = new ConsultaDao() {};
    
    int Buscar_P = -1;
    int Buscar_M = -1;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_principal_ = new javax.swing.JPanel();
        jdp_principal = new javax.swing.JDesktopPane();
        jButton_cadastrar_ = new javax.swing.JButton();
        jButton_fechar_ = new javax.swing.JButton();
        jLabel_cadastroPaciente = new javax.swing.JLabel();
        jLabel_Exame = new javax.swing.JLabel();
        jLabel_nomeExame = new javax.swing.JLabel();
        jTextField_nomeExame = new javax.swing.JTextField();
        jLabel_desExame = new javax.swing.JLabel();
        jTextField_DescricaoExame = new javax.swing.JTextField();
        jLabel_valorConsulta = new javax.swing.JLabel();
        jTextField_ValorConsulta = new javax.swing.JTextField();
        jLabel_peso = new javax.swing.JLabel();
        jTextField_motivoConsulta = new javax.swing.JTextField();
        jLabel_dataConsulta = new javax.swing.JLabel();
        jTextField_dataConsulta = new javax.swing.JTextField();
        jLabel_TITULO = new javax.swing.JLabel();
        jLabel_consulta = new javax.swing.JLabel();
        jButton_CadastrarPaciente_ = new javax.swing.JButton();
        jButton_BuscarPaciente_ = new javax.swing.JButton();
        jButton_BuscarMedico_ = new javax.swing.JButton();
        jButton_Limpar_ = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_consultar = new javax.swing.JMenu();
        jMenuItem_Consultas_ = new javax.swing.JMenuItem();
        jMenuItem_ConsultarPaciente_ = new javax.swing.JMenuItem();
        jMenuItem_ConsultarMedico_ = new javax.swing.JMenuItem();
        jMenuItem_ConsultarUsuario_ = new javax.swing.JMenuItem();
        jMenu_CadastroMedico_ = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistemas Joelmir");
        setResizable(false);

        javax.swing.GroupLayout jPanel_principal_Layout = new javax.swing.GroupLayout(jPanel_principal_);
        jPanel_principal_.setLayout(jPanel_principal_Layout);
        jPanel_principal_Layout.setHorizontalGroup(
            jPanel_principal_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel_principal_Layout.setVerticalGroup(
            jPanel_principal_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jdp_principal.setBackground(java.awt.SystemColor.activeCaption);
        jdp_principal.setForeground(new java.awt.Color(51, 51, 51));
        jdp_principal.setName(""); // NOI18N

        jButton_cadastrar_.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jButton_cadastrar_.setText("Cadastrar");
        jButton_cadastrar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cadastrar_ActionPerformed(evt);
            }
        });

        jButton_fechar_.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jButton_fechar_.setText("Fechar");
        jButton_fechar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_fechar_ActionPerformed(evt);
            }
        });

        jLabel_cadastroPaciente.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel_cadastroPaciente.setText("Paciente:");

        jLabel_Exame.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel_Exame.setText("Exame do Paciente:");

        jLabel_nomeExame.setText("Nome Exame:");

        jLabel_desExame.setText("Descrição Exame:");

        jLabel_valorConsulta.setText("Valor Consulta:");

        jLabel_peso.setText("Motivo Consulta::");

        jLabel_dataConsulta.setText("Data Consulta:");

        jLabel_TITULO.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel_TITULO.setText("CADASTRO CONSULTAS:");

        jLabel_consulta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel_consulta.setText("Consulta:");

        jButton_CadastrarPaciente_.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jButton_CadastrarPaciente_.setText("Cadastrar Paciente");
        jButton_CadastrarPaciente_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CadastrarPaciente_ActionPerformed(evt);
            }
        });

        jButton_BuscarPaciente_.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jButton_BuscarPaciente_.setText("Buscar Paciente");
        jButton_BuscarPaciente_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarPaciente_ActionPerformed(evt);
            }
        });

        jButton_BuscarMedico_.setText("Medico");
        jButton_BuscarMedico_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarMedico_ActionPerformed(evt);
            }
        });

        jButton_Limpar_.setText("Limpar");
        jButton_Limpar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Limpar_ActionPerformed(evt);
            }
        });

        jdp_principal.setLayer(jButton_cadastrar_, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jButton_fechar_, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_cadastroPaciente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_Exame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_nomeExame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jTextField_nomeExame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_desExame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jTextField_DescricaoExame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_valorConsulta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jTextField_ValorConsulta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_peso, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jTextField_motivoConsulta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_dataConsulta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jTextField_dataConsulta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_TITULO, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_consulta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jButton_CadastrarPaciente_, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jButton_BuscarPaciente_, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jButton_BuscarMedico_, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jButton_Limpar_, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdp_principalLayout = new javax.swing.GroupLayout(jdp_principal);
        jdp_principal.setLayout(jdp_principalLayout);
        jdp_principalLayout.setHorizontalGroup(
            jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdp_principalLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdp_principalLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel_TITULO))
                    .addGroup(jdp_principalLayout.createSequentialGroup()
                        .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jdp_principalLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_cadastroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_consulta)))
                            .addComponent(jLabel_dataConsulta))
                        .addGap(68, 68, 68)
                        .addComponent(jTextField_dataConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jdp_principalLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jButton_CadastrarPaciente_)
                        .addGap(148, 148, 148)
                        .addComponent(jButton_BuscarPaciente_, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jdp_principalLayout.createSequentialGroup()
                            .addComponent(jLabel_peso)
                            .addGap(63, 63, 63)
                            .addComponent(jTextField_motivoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jdp_principalLayout.createSequentialGroup()
                            .addComponent(jLabel_valorConsulta)
                            .addGap(75, 75, 75)
                            .addComponent(jTextField_ValorConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdp_principalLayout.createSequentialGroup()
                        .addComponent(jLabel_Exame)
                        .addContainerGap(401, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdp_principalLayout.createSequentialGroup()
                        .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jdp_principalLayout.createSequentialGroup()
                                .addComponent(jLabel_nomeExame)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_nomeExame, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jdp_principalLayout.createSequentialGroup()
                                .addComponent(jLabel_desExame)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addComponent(jTextField_DescricaoExame, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdp_principalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_BuscarMedico_, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(jdp_principalLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jButton_cadastrar_, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167)
                .addComponent(jButton_Limpar_, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167)
                .addComponent(jButton_fechar_, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jdp_principalLayout.setVerticalGroup(
            jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdp_principalLayout.createSequentialGroup()
                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdp_principalLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel_TITULO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_cadastroPaciente))
                    .addGroup(jdp_principalLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel_Exame)))
                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdp_principalLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_CadastrarPaciente_)
                            .addComponent(jButton_BuscarPaciente_)))
                    .addGroup(jdp_principalLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_nomeExame)
                            .addComponent(jTextField_nomeExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdp_principalLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_desExame)
                            .addComponent(jTextField_DescricaoExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jdp_principalLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel_consulta)))
                .addGap(37, 37, 37)
                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_dataConsulta)
                    .addComponent(jTextField_dataConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_valorConsulta)
                    .addComponent(jTextField_ValorConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jButton_BuscarMedico_)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdp_principalLayout.createSequentialGroup()
                        .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_peso)
                            .addComponent(jTextField_motivoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81)
                        .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jdp_principalLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jButton_Limpar_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(9, 9, 9))
                            .addComponent(jButton_cadastrar_, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdp_principalLayout.createSequentialGroup()
                        .addComponent(jButton_fechar_)
                        .addGap(9, 9, 9)))
                .addContainerGap(315, Short.MAX_VALUE))
        );

        jMenu_consultar.setText("Consultar");
        jMenu_consultar.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jMenu_consultar.setMaximumSize(new java.awt.Dimension(150, 150));
        jMenu_consultar.setPreferredSize(new java.awt.Dimension(50, 50));

        jMenuItem_Consultas_.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        jMenuItem_Consultas_.setText("Historico Consultas");
        jMenuItem_Consultas_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Consultas_ActionPerformed(evt);
            }
        });
        jMenu_consultar.add(jMenuItem_Consultas_);

        jMenuItem_ConsultarPaciente_.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        jMenuItem_ConsultarPaciente_.setText("Paciente");
        jMenuItem_ConsultarPaciente_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ConsultarPaciente_ActionPerformed(evt);
            }
        });
        jMenu_consultar.add(jMenuItem_ConsultarPaciente_);

        jMenuItem_ConsultarMedico_.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        jMenuItem_ConsultarMedico_.setText("Medico");
        jMenuItem_ConsultarMedico_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ConsultarMedico_ActionPerformed(evt);
            }
        });
        jMenu_consultar.add(jMenuItem_ConsultarMedico_);

        jMenuItem_ConsultarUsuario_.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        jMenuItem_ConsultarUsuario_.setText("Usuario/Funcionario");
        jMenuItem_ConsultarUsuario_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ConsultarUsuario_ActionPerformed(evt);
            }
        });
        jMenu_consultar.add(jMenuItem_ConsultarUsuario_);

        jMenuBar1.add(jMenu_consultar);

        jMenu_CadastroMedico_.setText("Cadastrar Medico");
        jMenu_CadastroMedico_.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 18)); // NOI18N
        jMenu_CadastroMedico_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu_CadastroMedico_MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu_CadastroMedico_);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdp_principal)
                    .addComponent(jPanel_principal_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdp_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_principal_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_cadastrar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cadastrar_ActionPerformed
        
        ConsultaM c = this.MontarExame();
        Cdao.inserir(c);
        
        this.Limpar();
      
    }//GEN-LAST:event_jButton_cadastrar_ActionPerformed

    private void jButton_fechar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_fechar_ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton_fechar_ActionPerformed

    private void jButton_CadastrarPaciente_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CadastrarPaciente_ActionPerformed
        
        PacienteV v = new PacienteV();
        jdp_principal.add(v);
        v.setVisible(true);;
        
    }//GEN-LAST:event_jButton_CadastrarPaciente_ActionPerformed

    private void jButton_BuscarPaciente_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarPaciente_ActionPerformed
        
          //Para receber objetodentro de um metodo,esta variavel deve ser declarada como variavel global
         
         
         String CPF = JOptionPane.showInputDialog("Informe o CPF");
        String sqlId = "SELECT idpaciente FROM Paciente WHERE cpf = ?";
        
        try {
            PreparedStatement ps = conn.getConexao().prepareStatement(sqlId);
            ps.setString(1, CPF);
            ResultSet rs = ps.executeQuery();
            
            if (rs.next()) {
                Buscar_P = rs.getInt("idpaciente");
                JOptionPane.showMessageDialog(null, "Busca Confirmada ");
            }else{
                JOptionPane.showMessageDialog(null, "Paciente Não Cadastrado! ");
            }
            
            ps.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro SQL: " + ex.getMessage());
        }
        
    }//GEN-LAST:event_jButton_BuscarPaciente_ActionPerformed

    private void jButton_BuscarMedico_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarMedico_ActionPerformed
        
         
         
         String CPF = JOptionPane.showInputDialog("Informe o CPF");
        String sqlId = "SELECT idmedico FROM Medico WHERE cpf = ?";
        
        try {
            PreparedStatement ps = conn.getConexao().prepareStatement(sqlId);
            ps.setString(1, CPF);
            ResultSet rs = ps.executeQuery();
            
            if (rs.next()) {
                Buscar_M = rs.getInt("idmedico");
                JOptionPane.showMessageDialog(null, "Busca Confirmada ");
            }else{
                JOptionPane.showMessageDialog(null, "Medico Não Cadastrado! ");
            }
            
            ps.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro SQL: " + ex.getMessage());
        }
        
    }//GEN-LAST:event_jButton_BuscarMedico_ActionPerformed

    private void jMenuItem_ConsultarPaciente_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ConsultarPaciente_ActionPerformed
        
        ConsultarPaciente cp = new ConsultarPaciente();
        jdp_principal.add(cp);
        cp.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem_ConsultarPaciente_ActionPerformed

    private void jMenuItem_ConsultarMedico_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ConsultarMedico_ActionPerformed
        
        ConsultarMedico cm = new ConsultarMedico();
        jdp_principal.add(cm);
        cm.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem_ConsultarMedico_ActionPerformed

    private void jMenuItem_ConsultarUsuario_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ConsultarUsuario_ActionPerformed
        
        ConsultarFuncionario cf = new ConsultarFuncionario();
        jdp_principal.add(cf);
        cf.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem_ConsultarUsuario_ActionPerformed

    private void jMenu_CadastroMedico_MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_CadastroMedico_MousePressed
        
        Medico  m = new Medico();
        jdp_principal.add(m);
        m.setVisible(true);
        
    }//GEN-LAST:event_jMenu_CadastroMedico_MousePressed

    private void jButton_Limpar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Limpar_ActionPerformed
        Limpar();
    }//GEN-LAST:event_jButton_Limpar_ActionPerformed

    private void jMenuItem_Consultas_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Consultas_ActionPerformed
       
        ConConsultas c = new ConConsultas();
        jdp_principal.add(c);
        c.setVisible(true);
    }//GEN-LAST:event_jMenuItem_Consultas_ActionPerformed
    
    public void Limpar(){
        jTextField_dataConsulta.setText("");
        jTextField_ValorConsulta.setText("");
        jTextField_motivoConsulta.setText("");
        jTextField_nomeExame.setText("");
        jTextField_DescricaoExame.setText("");
    }
    
    public ConsultaM MontarExame(){
        ConsultaM e = new ConsultaM();
        e.setPaciente(Buscar_P);
        e.setDataconsulta(jTextField_dataConsulta.getText());
        e.setValorconsulta(Float.parseFloat(jTextField_ValorConsulta.getText()));
        e.setMotivoconsulta(jTextField_motivoConsulta.getText());
        e.setNomeexame(jTextField_nomeExame.getText());
        e.setDescricaoexame(jTextField_DescricaoExame.getText());
        e.setMedico(Buscar_M);
        return e;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_BuscarMedico_;
    private javax.swing.JButton jButton_BuscarPaciente_;
    private javax.swing.JButton jButton_CadastrarPaciente_;
    private javax.swing.JButton jButton_Limpar_;
    private javax.swing.JButton jButton_cadastrar_;
    private javax.swing.JButton jButton_fechar_;
    private javax.swing.JLabel jLabel_Exame;
    private javax.swing.JLabel jLabel_TITULO;
    private javax.swing.JLabel jLabel_cadastroPaciente;
    private javax.swing.JLabel jLabel_consulta;
    private javax.swing.JLabel jLabel_dataConsulta;
    private javax.swing.JLabel jLabel_desExame;
    private javax.swing.JLabel jLabel_nomeExame;
    private javax.swing.JLabel jLabel_peso;
    private javax.swing.JLabel jLabel_valorConsulta;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_ConsultarMedico_;
    private javax.swing.JMenuItem jMenuItem_ConsultarPaciente_;
    private javax.swing.JMenuItem jMenuItem_ConsultarUsuario_;
    private javax.swing.JMenuItem jMenuItem_Consultas_;
    private javax.swing.JMenu jMenu_CadastroMedico_;
    private javax.swing.JMenu jMenu_consultar;
    private javax.swing.JPanel jPanel_principal_;
    private javax.swing.JTextField jTextField_DescricaoExame;
    private javax.swing.JTextField jTextField_ValorConsulta;
    private javax.swing.JTextField jTextField_dataConsulta;
    private javax.swing.JTextField jTextField_motivoConsulta;
    private javax.swing.JTextField jTextField_nomeExame;
    private javax.swing.JDesktopPane jdp_principal;
    // End of variables declaration//GEN-END:variables
}
